USE `essentialmode`;

ALTER TABLE `users`
	ADD COLUMN `Nom` VARCHAR(50) NULL DEFAULT '',
	ADD COLUMN `Prenom` VARCHAR(50) NULL DEFAULT '',
	ADD COLUMN `Dateb de naissance` VARCHAR(25) NULL DEFAULT '',
	ADD COLUMN `Sex` VARCHAR(10) NULL DEFAULT '',
	ADD COLUMN `Taille` VARCHAR(5) NULL DEFAULT ''
;